package CA2;

import CA2.constants.MenuOption;

import java.util.Scanner;

public class ITCompanyApp {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        boolean employeeFileGenerated = false;

        System.out.println("Please enter company name:");
        String companyName = sc.nextLine();
        ITCompany company = new ITCompany(companyName);
        System.out.println("Company employees and managers have been autogenerated.");
        System.out.print("Would you like to write all of them to a file? Enter 0 for YES, or 1 for NO: ");
        int userChoice = Utils.getUserChoice(sc);

        if (userChoice == 0) {
            company.writeAllEmployeesToFile();
            System.out.println("All employees have been written to the employee.csv file.");
            employeeFileGenerated = true;
        } else {
            System.out.println("Employees have not been written to a file.");
        }

        do {
            System.out.printf("\n---- %s Company Menu ----\n", companyName);
            for (MenuOption option : MenuOption.values()) {
                System.out.println(option.getDescription());
            }

            System.out.print("Enter your choice:\n");
            while (!sc.hasNextInt()) {
                System.out.println("Invalid input! Please enter a number.");
                sc.next();
                System.out.print("Enter your choice: ");
            }

            userChoice = sc.nextInt();
            MenuOption selectedOption = MenuOption.fromCode(userChoice);

            if (selectedOption == null) {
                System.out.println("Invalid choice, please enter a number from 1 to 4.");
                continue;
            }
            // clear scanner
//            sc.nextLine();

            switch (selectedOption) {
                case SORT -> {
                    System.out.println("Which file would you like to sort? Enter 0 for EMPLOYEE file or 1 for APPLICANTS file?");
                    if (!employeeFileGenerated) {
                        System.out.println("If you enter 0 employee.csv file will be created and all employees will be written to it.");
                    }

                    userChoice = Utils.getUserChoice(sc);

                    if (userChoice == 0) {
                        if (!employeeFileGenerated) {
                            System.out.println("Writing all " + companyName + " Company employees to employee.csv file ...");
                            company.writeAllEmployeesToFile();
                        }
                        company.sortAndPrintEmployees();
                    } else {
                        Utils.sortAndPrintApplicantsFile(20, 0);
                    }
                }
                case SEARCH -> {
                    sc.nextLine();
                    System.out.println("Which file would you like to search? Enter 0 for EMPLOYEE file or 1 for APPLICANTS file?");
                    if (!employeeFileGenerated) {
                        System.out.println("If you enter 0 employee.csv file will be created and all employees will be written to it.");
                    }

                    userChoice = Utils.getUserChoice(sc);
                    System.out.println("To search by First Name - enter 0, by Last Name - enter 1:");
                    int sortOption = Utils.getUserChoice(sc);
                    System.out.print("Enter your search query: ");
                    String query = sc.nextLine();

                    if (userChoice == 0) {
                        if (!employeeFileGenerated) {
                            System.out.println("Writing all " + companyName + " Company employees to employee.csv file ...");
                            company.writeAllEmployeesToFile();
                            employeeFileGenerated = true;
                        }
                        company.searchEmployee(query, sortOption);
                    } else {
                        Utils.searchAndPrintApplicants(query, sortOption);
                    }
                }
                case ADD -> Utils.generateRandomEmployee("Austin", "Adiabese", company.getITDepartment());
                case EXIT -> System.out.println("Exiting...");
            }
        } while (userChoice != MenuOption.EXIT.getCode());

        sc.close();
    }
}
